### ISSUE TITLE
Standardize output order and nomenclature

### ISSUE THREAD

**Issue by jmason42** [CovertLab/arrow#10]
For simulation functions, I think the output should be the more standard (independent variable, dependent variables) pattern.  E.g. time, and then counts.

In the single-step case, this would be the time of reaction, and then the counts (as a 1D integer vector) at the end of the step.

For a run-until case, it should be the time-histories, and then the count-histories (as a 2D integer vector with time points on the major axis).

**Comment by jmason42** [comment]
Forgot to mention: as a pattern of usage, I think we should be doing

```
(time, counts) = <whatever function is called>
```

to standardize output variable names.  I think it's a good trade-off between exactitude and generality.

**Comment by prismofeverything** [comment]
Agreed, I picked arbitrarily so if you have a reason for one or the other please feel free.

**Comment by jmason42** [comment]
Addressed by #22
