### ISSUE TITLE
Release versioning

### ISSUE THREAD

**Issue by jmason42** [CovertLab/arrow#21]
It's early days yet but I think it would be good to establish some means of communicating 'stable' release versions vs. the unstable development versions.  I think there are a few different ways to do this but as a first step we could try GitHub's built-in release feature (https://github.com/CovertLab/arrow/releases) which seems to use tags.

**Comment by prismofeverything** [comment]
Totally, once we merge your PR we can make a 0.0.4 release and post it on the releases page on github. I have a pypi account now so another cool step would be to automate deployment upon release, but maybe we don't need to get too fancy.

**Comment by jmason42** [comment]
I think we can hold off on auto-deployment until a hypothetical v0.1, but I like the idea.
