### ISSUE TITLE
Suspend alternative propensity calculation 'form's

### ISSUE THREAD

**Issue by jmason42** [CovertLab/arrow#27]
Playing with Numba - I don't think it likes passing around function handles.  I get performance hits when trying to wrap `propensity` and `choose` with `@numba.jit`, but if I pull out the `form` option, I get roughly a four-fold speed-up.  There's probably a way around this but I think it's going to be easier to step back before moving forward - we also don't have any non-default test cases for the `form` feature.  @prismofeverything thoughts?

(Numba [FAQs](https://numba.pydata.org/numba-doc/dev/user/faq.html) suggest that this is an active area for improvement.)

**Comment by prismofeverything** [comment]
Yeah I'm happy to walk back the `form` feature if it is holding us back, feel free! It was for a feature Heejo needed, but it turns out she doesn't need it anymore

**Comment by jmason42** [comment]
Addressed via #28.
