### ISSUE TITLE
Moving distribution plots

### ISSUE THREAD

**Issue by jmason42** [CovertLab/arrow#3]
Long stochastic simulations, or simulations with multiple components, aren't practical for plotting.  Downsampling is an ugly and risky approach (e.g. downsampling at even-numbered intervals a strictly alternating pair of reactions); plotting a moving average, or even a moving distribution (e.g. mean and mean +/- standard deviation) would be better, and those lines could be downsampled in a sane/controlled fashion (e.g. via the RDP algorithm).

Open questions:
- What is the right distribution to plot?  Mean +/- standard deviation could look odd near the low molecule number limits (i.e. could go negative), in which case moving average may be all we really want.  What about a moving min/median/max?
- How to handle the leading edge?  In other words, how do we initialize the moving averages (or other quantities)?  This is a general problem with convolution-based approaches to data processing.

**Comment by prismofeverything** [comment]
This is a good point, and to answer your open questions I would just say let's try a bunch of things and see what works. Ultimately we will probably need a few options so that people can customize the plot to their taste (while choosing parsimonious defaults of course).

**Comment by jmason42** [comment]
Partly addressed via #18.  New features can be brought in as needed.
