### ISSUE TITLE
Name conflict with Jupyter dependency

### ISSUE THREAD

**Issue by thalassemia** [CovertLab/arrow#51]
To install Jupyter, the following chain of dependencies is pulled in:
```
jupyter --> notebook --> nbclassic --> jupyter-server --> jupyter-events --> jsonschema[format-nongpl] --> isoduration --> arrow
``` 

I've linked the repo for the conflicting [`arrow`](https://github.com/arrow-py/arrow) package.

Any suggestions are welcome!

**Comment by 1fish2** [comment]
Ugh.

* This new `arrow` pip is (yet another) date-time package.
* `pip install numpy; pip install jupyter stochastic-arrow` doesn't complain, but `arrow` won over `stochastic_arrow` for the `arrow/` library directory:
  ```
  $ cd /usr/local/var/pyenv/versions/jupyter-conflict/lib/python3.11/site-packages
  $ ll -d *arrow*
  drwxr-xr-x  17 jerry  admin   544B Jun 27 19:12 arrow/
  drwxr-xr-x   8 jerry  admin   256B Jun 27 19:12 arrow-1.2.3.dist-info/
  drwxr-xr-x   9 jerry  admin   288B Jun 27 19:12 stochastic_arrow-0.5.2.dist-info/
  ```
* `import arrow` now imports the date-time package.
* The `stochastic-arrow` installation is broken.

Workarounds that I can think of:
1. Rename the `stochastic-arrow` library so we'd do `from stochastic_arrow import StochasticSystem`, then update wcEcoli and vivarium-ecoli.
2. Workaround the site-packages conflict somehow and some predictable way, then manipulate python's `sys.path` before importing one of them. (This can only lead to greif.)
3. Don't use Jupyter and stochastic_arrow together :)

Unless anyone (including @prismofeverything @U8NWXD @eagmon) has a better idea, it's gotta be # 1 .

@thalassemia do you want to be one of the PyPI package maintainers for this library?

**Comment by prismofeverything** [comment]
I'm all for #1.... should have changed the directory name along with the
package name when we found out there was already another package named
`arrow` --- lesson learned!

Got to love the wild west of global namespaces. More fun to be early
really, pypi is getting crowded.

**Comment by 1fish2** [comment]
Indeed, let's rename just the directory (module) to `stochastic_arrow` and keep the package name `stochastic-arrow` (although in retrospect I think PyPI should require them to match), or nest the module, `stochastic_arrow.arrow`.

**Comment by thalassemia** [comment]
I noticed that [`test_flagella`](https://github.com/CovertLab/arrow/blob/fdf3db7ae09a59501c4d8fcc2b5430b9f48e8be1/arrow/test/test_arrow.py#L248) fails locally both on `master` and my PR. Is this expected behavior?

**Comment by 1fish2** [comment]
Yes, we discussed test_flagella failing [in PR 47](https://github.com/CovertLab/arrow/pull/47#issuecomment-952227030) and [in PR 49](https://github.com/CovertLab/arrow/pull/49#pullrequestreview-835815489). It needs debugging. What change broke it?

IIRC, the memory leak test is not solid.

**Comment by 1fish2** [comment]
When we move to Mojo🔥, we won't need Cython :)

**Comment by thalassemia** [comment]
Looking through the Git history, `test_flagella` was added in c91d6fe, which seems intended to provide more information during a simulation failure. I think the test failing is intentional. I renamed it `fail_test_flagella` in my PR so `pytest` does not automatically run it.

**Comment by 1fish2** [comment]
Ah. You created the GitHub release. I'll build and push to PyPI.

**Comment by 1fish2** [comment]
There it is: https://pypi.org/project/stochastic-arrow/1.0.0/

I guess I'll update wcEcoli.
