### ISSUE TITLE
E. coli WCM complexation test system

### ISSUE THREAD

**Issue by jmason42** [CovertLab/arrow#9]
For this package to be competitive, we need a big, messy system to implement, and some performance targets.  The speculative SSA *E. coli* complexation process is an obvious case, as it was a motivating problem for this package.  It may not need to be *in* the repository but some form should be accessible for development purposes.

**Comment by prismofeverything** [comment]
Working on it!

**Comment by prismofeverything** [comment]
Just pushed a test of complexation. Basically I took the stoichiometry and the molecule counts before and after one time step and saved them out, then loaded them into a new test and compared them. As I raise the value of `rates` the simulation gets more accurate (differences between `outcome` and `expected` decrease), but also there is a threshold around 4 where the simulation just stops running. Looking into this now.

I have added two plots to the test. Also, @jmason42 you may not have realized I am using pytest and you can run the tests at the commandline by saying 

    > pytest

I will add something to the README about this.

**Comment by prismofeverything** [comment]
Okay, I worked out the issue by correctly handling the case where no more events can take place and therefore the `dt` is 0, now we can use any rates for the complexation reactions. With these changes I get 0 differences between the behavior of complexation in the WCM and complexation using arrow. If the rate is "10" these 114 events occur in ~0.5 seconds. If the rate is "1000000" it completes in 4.6e-6 seconds.

**Comment by jmason42** [comment]
> @jmason42 you may not have realized I am using pytest
Indeed I did not, but good to know.  I will start making a habit of writing tests.

> Okay, I worked out the issue by correctly handling the case where no more events can take place and therefore the dt is 0, now we can use any rates for the complexation reactions.
Ah, right, otherwise your expected time for the next event shoots off to infinity.  Will take a look at it, thanks for bringing that in.

**Comment by jmason42** [comment]
OK, this looks useful.  Closing.
